### ISSUE TITLE
Set position sometimes fails

### ISSUE THREAD

**Issue by mfld-fr** [rickhousley/happn#9]
Hello,

While testing a script to change periodically the position inside a region of interest, I have a strange behavior of the Happn API : it accepts the POST request the first time, then rejects the second time, and so on... whatever the delay between the requests (up to 15 minutes)...

The problem occurs with both the "rect bissect" and "square spiral" algorithms. I could have suspected a fake position detection on the first, but not on the second that moves the position like a real user (no huge jump in a step).

Any idea ?

**Comment by rickhousley** [comment]
They're likely rate limiting that endpoint now. I would suggest determining the timeout and only trying to change the position after that timeout. I have a theory though that if you create a new device with the happn id you'll be able to POST a distance under that window. -untested, but it may help

**Comment by mfld-fr** [comment]
OK, will try to increase again the time between two positions to see if it solves the issue.

What do you mean exactly by "create a new device with the happn id" ? Which "happn id" are you talking about ? User ID, device ID, other ?

**Comment by rickhousley** [comment]
Device ID. I think that if you create a new device every time (not implemented in API here) then you may be able to set that new device's location without having to wait for the timeout to complete. I haven't tested it, and I'm not exactly sure what the process for creating a new device is: i'd have to bust out burp suite again to check. Maybe this summer I'll do this.

**Comment by skipperbent** [comment]
I'm almost certain it's due to a limitation in the endpoint, most likely to decrease the chance of stalking someone in realtime. The question is if the limitation is bound to the device or the user. If the limitation is bound to the device, changing the device-id like suggested above might help - otherwise you could have several users harvesting data - depending on the setup and purpose of your app.

**Comment by mfld-fr** [comment]
I ran the script _"square-spiral"_ all the night long, this time with a 30 minutes delay (my previous test was with 15 mins, see above). All the position changes were accepted by Happn :smile: .

There was also the new header "X-Happn-DID" in this latest version of the script (from the `php` branch), to follow the above suggestions. I cannot say if it had an effect or not (should have decoupled the two changes...).

@springjools also reported a behaviour that could be linked with the real position (Happn could check with the data from GM ?!?). To be checked.

**Comment by springjools** [comment]
Before the api change at least, the timeout between position changes would only be as high as 10 or 20 minutes if you tried to flood those requests. It was possible to change position every minute or so, and the higher timeout was a penalty if you say so for not complying.

**Comment by mfld-fr** [comment]
Looks like something changed again recently on server side, because set position fails again after working very well with the same & previous settings in PHP modules...

By the way, I noticed we had a visit from "redmine.happn.com"...

**Comment by springjools** [comment]
Hi,

Yes, that was the other reason I didn't want to put all code public to
github, but I guess I thought I was being paranoid.

/P

**Comment by springjools** [comment]
Works mostly here, although I get frequently 504 error (gateway timed out).

To the question whether the position limitation is on device or user: to me it seems that the device is a property of the user object, and maybe you can create more devices to bypass the limit check, but I would like to point out that the position limit is on the server and not client. Meaning that the http query will give you a position and no errors, but sometimes this is an old position. I have noticed by following myself. 

It also means that some matches (collisions) that you get are actually not because you were actually close to the other person in real life, but because the positions on the server were. So the whole premise of the app is to have real-time collisions but I don't think it really works that way. Sometimes if you drive a car, your position can be "stuck" under a bridge or something for like 20 hours,and you can query this position accurately from the server, but nonetheless it has little bearing in real life.

Unless there is some other error that I'm missing, like incompatible gps coordinates, geodetic datum or something like this. You know that there are diverging standards for these, not everyone uses WGS84 for example.

**Comment by mfld-fr** [comment]
I think I understood what happn-ed :smiley:

Result of device list query: GET /api/users/XXXXX/devices/
array(5) { ["success"]=> bool(true) ["status"]=> int(200) ["error"]=> NULL ["data"]=> array(0) { } ["error_code"]=> int(0) } 

Looks like Happn forgot my device, or the registered device is deleted after a given time.

As device creation process is not understood yet, solution is to run the official application again.
